// Code generated by Kitex v0.0.8. DO NOT EDIT.
package transaction

import (
	"github.com/cloudwego/kitex/server"
	"tx_demo/kitex_gen/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.Transaction, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
